export const templates = [
    {
        id: 'nature-greenery',
        name: 'Nature Greenery',
        price: 99,
        previewImage: '/previews/front/nature-greenery.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Environmental Consultant',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Georgia',
            layout: 'center',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/15.png',
            logoPreview: null,
            backTextColor: '#ffffff',
            backLayout: 'center',
            backName: 'Company Name',
            backTitle: 'Sustainable Futures',
            backEmail: 'info@example.com',
            backPhone: '800-555-0199',
            backUploadType: 'logo',
            nfcIcon: true,
        },
    },
    {
        id: 'google-review-blue',
        name: 'Google Review - Blue',
        price: 99,
        previewImage: '/previews/front/google-review-blue.png',
        design: {
            cardColor: '#4285F4',
            textColor: '#ffffff',
            name: 'Review Us on Google',
            title: '⭐⭐⭐⭐⭐',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'center',
            logoPreview: '/google.png',
            backgroundType: 'color',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Scan To Review',
            nfcIcon: true,
        },
    },
    {
        id: 'urban-night',
        name: 'Urban Night',
        price: 99,
        previewImage: '/previews/front/urban-night.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Urban Explorer',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'right',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/11.png',
            logoPreview: null,
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Connect With Me',
            nfcIcon: true,
        },
    },
    {
        id: 'oceanic-waves',
        name: 'Oceanic Waves',
        price: 99,
        previewImage: '/previews/front/oceanic-waves.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#000000',
            name: 'Your Name',
            title: 'Oceanographer',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Georgia',
            layout: 'left',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/21.png',
            logoPreview: null,
            backTextColor: '#000000',
            backLayout: 'center',
            backName: 'Company Name',
            backTitle: 'Exploring the Deep',
            backEmail: 'info@example.com',
            backPhone: '800-555-0199',
            backUploadType: 'logo',
            nfcIcon: true,
        },
    },
    {
        id: 'geometric-patterns',
        name: 'Geometric Patterns',
        price: 99,
        previewImage: '/previews/front/geometric-patterns.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#000000',
            name: 'Your Name',
            title: 'Architect | Designer',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Arial',
            layout: 'center',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/22.png',
            logoPreview: null,
            backTextColor: '#000000',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'View My Portfolio',
            nfcIcon: true,
        },
    },
    {
        id: 'mountain-vista',
        name: 'Mountain Vista',
        price: 99,
        previewImage: '/previews/front/mountain-vista.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Adventure Guide',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'center',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/14.png',
            logoPreview: null,
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            backName: 'Peak Adventures',
            nfcIcon: true,
        },
    },
    {
        id: 'marble-elegance',
        name: 'Marble Elegance',
        price: 99,
        previewImage: '/previews/front/marble-elegance.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#333333',
            name: 'Your Name',
            title: 'Interior Designer',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Georgia',
            layout: 'center',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/23.png',
            logoPreview: null,
            backTextColor: '#333333',
            backLayout: 'center',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            backName: 'Design Studio',
            nfcIcon: true,
        },
    },
    {
        id: 'dark-woodgrain',
        name: 'Dark Woodgrain',
        price: 99,
        previewImage: '/previews/front/dark-woodgrain.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Artisan Carpenter',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'left',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/13.png',
            logoPreview: null,
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'See My Work',
            nfcIcon: true,
        },
    },
    {
        id: 'watercolor-splash',
        name: 'Watercolor Splash',
        price: 99,
        previewImage: '/previews/front/watercolor-splash.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#2c3e50',
            name: 'Your Name',
            title: 'Artist & Illustrator',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Georgia',
            layout: 'center',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/25.png',
            logoPreview: null,
            backTextColor: '#2c3e50',
            backLayout: 'center',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            backName: 'Art Studio',
            nfcIcon: true,
        },
    },
    {
        id: 'modern-dark',
        name: 'Modern Dark',
        price: 99,
        previewImage: '/previews/front/modern-dark.png',
        design: {
            cardColor: '#1a1a1a',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Your Title',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'left',
            backgroundType: 'color',
            logoPreview: '/logo.png',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            backName: 'Your Company',
            nfcIcon: true,
        },
    },
    {
        id: 'classic-professional',
        name: 'Classic Professional',
        price: 99,
        previewImage: '/previews/front/classic-professional.png',
        design: {
            cardColor: '#EAEAEA',
            textColor: '#333333',
            name: 'Your Name',
            title: 'Your Title',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Times New Roman',
            layout: 'right',
            backgroundType: 'color',
            backTextColor: '#333333',
            backLayout: 'center',
            backName: 'Company Name',
            backTitle: 'Company Slogan or Mission Statement',
            backEmail: 'info@example.com',
            backPhone: '800-555-0199',
            backUploadType: 'logo',
            nfcIcon: true,
        },
    },
    {
        id: 'Google Review',
        name: 'Google Review',
        price: 99,
        previewImage: '/previews/front/google-review.png',
        design: {
            cardColor: '#EAEAEA',
            textColor: '#333333',
            name: 'Review Us on Google',
            title: '⭐⭐⭐⭐⭐',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Times New Roman',
            layout: 'center',
            logoPreview: '/google.png',
            backgroundType: 'color',
            backTextColor: '#333333',
            backLayout: 'center',
            backName: 'Scan To Review',
            backTitle: 'Company Name',
            backEmail: 'info@example.com',
            backPhone: '800-555-0199',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            nfcIcon: true,
        },
    },
    {
        id: 'vibrant-gradient',
        name: 'Vibrant Gradient',
        price: 99,
        previewImage: '/previews/front/vibrant-gradient.png',
        design: {
            cardColor: '#ff7e5f',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Creative Designer',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'center',
            backgroundType: 'color',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Connect With Me',
            nfcIcon: true,
        },
    },
    {
        id: 'eco-friendly-kraft',
        name: 'Eco-Friendly Kraft',
        price: 99,
        previewImage: '/previews/front/eco-friendly-kraft.png',
        design: {
            cardColor: '#d2b48c',
            textColor: '#3a2d0d',
            name: 'Your Name',
            title: 'Sustainable Solutions',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Courier New',
            layout: 'left',
            backgroundType: 'color',
            logoPreview: '/logo.png',
            backTextColor: '#3a2d0d',
            backLayout: 'center',
            backName: 'Eco Company',
            backTitle: 'Committed to Sustainability',
            backEmail: 'contact@eco.co',
            backPhone: '800-ECO-SAVE',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            nfcIcon: true,
        },
    },
    {
        id: 'techy-blue',
        name: 'Techy Blue',
        price: 99,
        previewImage: '/previews/front/techy-blue.png',
        design: {
            cardColor: '#0f2027',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Tech Innovator',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'right',
            backgroundType: 'color',
            logoPreview: '/logo.png',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Scan Me',
            nfcIcon: true,
        },
    },
    {
        id: 'bold-modern-red',
        name: 'Bold & Modern Red',
        price: 99,
        previewImage: '/previews/front/bold-modern-red.png',
        design: {
            cardColor: '#c0392b',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Innovator',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'center',
            backgroundType: 'color',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Connect With Me',
            nfcIcon: true,
        },
    },
    {
        id: 'clean-simple-gray',
        name: 'Clean & Simple Gray',
        price: 99,
        previewImage: '/previews/front/clean-simple-gray.png',
        design: {
            cardColor: '#f8f9fa',
            textColor: '#212529',
            name: 'Your Name',
            title: 'Consultant',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Arial',
            layout: 'left',
            backgroundType: 'color',
            logoPreview: '/logo.png',
            backTextColor: '#212529',
            backLayout: 'left',
            backName: 'Your Company',
            backTitle: 'Professional Consulting',
            backEmail: 'contact@consult.com',
            backPhone: '800-PRO-HELP',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            nfcIcon: true,
        },
    },
    {
        id: 'elegant-gold',
        name: 'Elegant Gold',
        price: 99,
        previewImage: '/previews/front/elegant-gold.png',
        design: {
            cardColor: '#000000',
            textColor: '#d4af37',
            name: 'Your Name',
            title: 'Luxury Specialist',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Georgia',
            layout: 'center',
            backgroundType: 'color',
            backTextColor: '#d4af37',
            backLayout: 'center',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            backName: 'Premium Services',
            nfcIcon: true,
        },
    },
    {
        id: 'oceanic-blue',
        name: 'Oceanic Blue',
        price: 99,
        previewImage: '/previews/front/oceanic-blue.png',
        design: {
            cardColor: '#004e92',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Marine Biologist',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'left',
            backgroundType: 'color',
            logoPreview: '/logo.png',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Explore My Work',
            nfcIcon: true,
        },
    },
    {
        id: 'sunny-yellow',
        name: 'Sunny Yellow',
        price: 99,
        previewImage: '/previews/front/sunny-yellow.png',
        design: {
            cardColor: '#ffc845',
            textColor: '#4a4a4a',
            name: 'Your Name',
            title: 'Marketing Guru',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Arial',
            layout: 'center',
            backgroundType: 'color',
            backTextColor: '#4a4a4a',
            backLayout: 'center',
            backUploadType: 'logo',
            backLogoPreview: '/logo.png',
            backName: 'Bright Ideas Inc.',
            nfcIcon: true,
        },
    },
    {
        id: 'minty-fresh',
        name: 'Minty Fresh',
        price: 99,
        previewImage: '/previews/front/minty-fresh.png',
        design: {
            cardColor: '#98ff98',
            textColor: '#004d00',
            name: 'Your Name',
            title: 'Wellness Coach',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Georgia',
            layout: 'right',
            backgroundType: 'color',
            logoPreview: '/logo.png',
            backTextColor: '#004d00',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Start Your Journey',
            nfcIcon: true,
        },
    },
    {
        id: 'google-review-white',
        name: 'Google Review - White',
        price: 99,
        previewImage: '/previews/front/google-review-white.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#000000',
            name: 'Review Us on Google',
            title: '⭐⭐⭐⭐⭐',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Arial',
            layout: 'center',
            logoPreview: '/google.png',
            backgroundType: 'color',
            backTextColor: '#000000',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Scan To Review',
            nfcIcon: true,
        },
    },
    {
        id: 'google-review-dark',
        name: 'Google Review - Dark',
        price: 99,
        previewImage: '/previews/front/google-review-dark.png',
        design: {
            cardColor: '#1a1a1a',
            textColor: '#ffffff',
            name: 'Review Us on Google',
            title: '⭐⭐⭐⭐⭐',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'center',
            logoPreview: '/google.png',
            backgroundType: 'color',
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Scan To Review',
            nfcIcon: true,
        },
    },
    {
        id: 'abstract-tech',
        name: 'Abstract Tech',
        price: 99,
        previewImage: '/previews/front/abstract-tech.png',
        design: {
            cardColor: '#ffffff',
            textColor: '#ffffff',
            name: 'Your Name',
            title: 'Futurist | Innovator',
            phone: '123-456-7890',
            email: 'your.email@example.com',
            fontFamily: 'Verdana',
            layout: 'center',
            backgroundType: 'image',
            backgroundImagePreview: '/backgrounds/1.png',
            logoPreview: null,
            backTextColor: '#ffffff',
            backLayout: 'center',
            backUploadType: 'qr',
            backLogoPreview: '/QR.png',
            backName: 'Connect & Innovate',
            nfcIcon: true,
        },
    },
];